# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x07\n\x05\x45mpty\"%\n\tTaskReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\")\n\rResultRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2|\n\x0eMessageService\x12\x1d\n\x07GetTask\x12\x06.Empty\x1a\n.TaskReply\x12$\n\nSendResult\x12\x0e.ResultRequest\x1a\x06.Empty\x12%\n\x0bProcessTask\x12\n.TaskReply\x1a\n.TaskReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_TASKREPLY']._serialized_start=26
  _globals['_TASKREPLY']._serialized_end=63
  _globals['_RESULTREQUEST']._serialized_start=65
  _globals['_RESULTREQUEST']._serialized_end=106
  _globals['_MESSAGESERVICE']._serialized_start=108
  _globals['_MESSAGESERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
